server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8061/eureka/
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n'
custom:
  message: This is employee service with project default
# for development; POST /actuator/refresh
management:
  endpoints:
    web:
      exposure:
        include: refresh